"use client";

import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export default function Disclaimer() {
  return (
    <div className="min-h-screen bg-white dark:bg-slate-950 pt-20 pb-20">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <Link href="/" className="inline-flex items-center gap-2 text-blue-600 hover:text-blue-700 mb-6">
          <ArrowLeft className="w-4 h-4" />
          Back to Home
        </Link>
        <h1 className="text-4xl font-bold text-slate-900 dark:text-white mb-4">Disclaimer</h1>
        <p className="text-slate-600 dark:text-slate-400 mb-8">Last updated: {new Date().toLocaleDateString()}</p>

        <div className="space-y-8 text-slate-700 dark:text-slate-300">
          <section>
            <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">1. General Disclaimer</h2>
            <p>
              The information provided on Echelon is for general informational purposes only. While we strive to keep information accurate and up to date, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability, or availability of the information contained on the website or related services.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">2. No Professional Advice</h2>
            <p>
              Echelon is not designed to provide professional advice, including but not limited to medical, legal, financial, or psychological advice. Any information provided should not be considered as a substitute for professional consultation. Always consult with qualified professionals before making important decisions based on information from our service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">3. AI-Generated Content Disclaimer</h2>
            <p className="mb-4">
              Echelon uses artificial intelligence to generate suggestions, insights, and recommendations. Please note:
            </p>
            <ul className="list-disc list-inside space-y-2">
              <li>AI-generated content may not always be accurate, complete, or appropriate for your specific situation</li>
              <li>You should verify any information provided by our AI assistant with reliable sources</li>
              <li>The AI may make mistakes or have limitations in understanding complex scenarios</li>
              <li>We are not responsible for any decisions made based solely on AI recommendations</li>
              <li>Always use your judgment and seek professional advice when appropriate</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">4. Data Accuracy</h2>
            <p>
              While we strive to maintain accurate data and analytics, we do not guarantee the accuracy of any calculations, projections, or insights generated by Echelon. Users are responsible for verifying the accuracy of their input data and the resulting outputs.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">5. Limitation of Liability</h2>
            <p>
              To the fullest extent permitted by law, Echelon and its creators shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of or inability to use the service, including but not limited to:
            </p>
            <ul className="list-disc list-inside space-y-2 mt-4">
              <li>Loss of data or productivity</li>
              <li>Financial losses</li>
              <li>Emotional distress or psychological harm</li>
              <li>Any damage to your device or software</li>
              <li>Interruption of service or access</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">6. Third-Party Services</h2>
            <p>
              Echelon integrates with third-party services such as Supabase, OpenAI, and other platforms. We are not responsible for:
            </p>
            <ul className="list-disc list-inside space-y-2 mt-4">
              <li>The accuracy or reliability of third-party services</li>
              <li>Any downtime or service interruptions from third parties</li>
              <li>The privacy practices of third-party services</li>
              <li>Any damage caused by third-party integrations</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">7. User Responsibility</h2>
            <p className="mb-4">
              You are responsible for:
            </p>
            <ul className="list-disc list-inside space-y-2">
              <li>Maintaining the confidentiality of your account credentials</li>
              <li>The security of your device and internet connection</li>
              <li>Backing up your data regularly</li>
              <li>Reviewing and understanding the terms of service</li>
              <li>Using the service in compliance with applicable laws</li>
              <li>Verifying any information before relying on it for important decisions</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">8. Service Availability</h2>
            <p>
              While we strive to maintain service availability, Echelon is provided on an "as-is" basis. We do not guarantee uninterrupted access or that the service will be error-free. We may perform maintenance or updates that could temporarily interrupt service without prior notice.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">9. No Warranty</h2>
            <p>
              The service is provided without any warranties, express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, or non-infringement of intellectual property rights. We make no warranty that the service will meet your requirements or that it will be suitable for any particular purpose.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">10. External Links</h2>
            <p>
              Echelon may contain links to external websites and resources. We are not responsible for the content, accuracy, or practices of these external sites. Your use of external links is at your own risk and subject to their terms of service and privacy policies.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">11. Changes to Service</h2>
            <p>
              We reserve the right to modify, update, or discontinue any aspect of Echelon at any time without notice. Changes to the service may affect the functionality you rely on, and we are not responsible for any adverse effects resulting from such changes.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">12. User-Generated Content</h2>
            <p>
              You are solely responsible for any content (tasks, notes, conversations) you create or upload to Echelon. We are not liable for any consequences resulting from your user-generated content, including data loss, privacy violations, or any other issues.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">13. Governing Law</h2>
            <p>
              This disclaimer is governed by and construed in accordance with applicable law. Any disputes arising from the use of Echelon shall be resolved in accordance with the applicable jurisdiction.
            </p>
          </section>

          <section className="mt-12 pt-8 border-t border-slate-200 dark:border-slate-800">
            <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">14. Important Notice</h2>
            <p className="p-4 bg-blue-50 dark:bg-blue-950/20 border border-blue-200 dark:border-blue-900 rounded-lg">
              By using Echelon, you acknowledge that you have read this disclaimer, understand its terms, and agree to assume all risks associated with the use of the service. If you do not agree with any part of this disclaimer, please discontinue use of Echelon immediately.
            </p>
          </section>

          <section className="mt-12 pt-8 border-t border-slate-200 dark:border-slate-800">
            <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">Questions?</h2>
            <p>
              If you have questions about our Disclaimer, please contact us at{' '}
              <a href="mailto:islamannafi@gmail.com" className="text-blue-600 hover:text-blue-700 dark:text-blue-400 dark:hover:text-blue-300">
                islamannafi@gmail.com
              </a>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}